# Generated by Django 4.2.2 on 2023-06-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='status',
            new_name='status_exact',
        ),
    ]
